apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-contact-points
  labels:
    grafana_alert_notification: "1"
data:
  contact_points.yaml: |-
    notifiers:
      - name: EmailContactPoint
        type: email
        uid: email_contact_point
        settings:
          addresses: 'your-email@example.com', "other-email@example.com"
